# Generated by Django 4.1.3 on 2022-11-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_individu_spouses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Individu',
        ),
    ]
