# Generated by Django 4.1.3 on 2022-12-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_individu_aboutme_individu_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='spouses',
            field=models.ManyToManyField(blank=True, to='main.individu'),
        ),
    ]
