# Generated by Django 4.1.3 on 2023-01-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_individu_isincomingspouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.ImageField(blank=True, null=True, upload_to='uploaded/')),
            ],
        ),
        migrations.AddField(
            model_name='individu',
            name='photoName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individu',
            name='photoPath',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
