# Generated by Django 4.1.3 on 2023-01-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_individu_sfather_individu_smother'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individu',
            old_name='sFather',
            new_name='sFatherName',
        ),
        migrations.RenameField(
            model_name='individu',
            old_name='sMother',
            new_name='sMotherName',
        ),
        migrations.AddField(
            model_name='individu',
            name='sFatherDead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individu',
            name='sMotherDead',
            field=models.BooleanField(default=False),
        ),
    ]
