# Generated by Django 4.1.3 on 2022-11-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generation', models.IntegerField()),
                ('parentMale', models.IntegerField()),
                ('parentFemale', models.IntegerField()),
                ('birth_rank', models.IntegerField()),
            ],
        ),
    ]
