# Generated by Django 4.1.3 on 2022-11-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_individu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Individu',
        ),
    ]
