# Generated by Django 4.1.3 on 2022-11-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_individu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=5)),
                ('generation', models.IntegerField()),
                ('parent_male_id', models.IntegerField()),
                ('parent_female_id', models.IntegerField()),
                ('birth_rank', models.IntegerField()),
                ('spouses', models.ManyToManyField(to='main.individu')),
            ],
        ),
    ]
