# Generated by Django 4.1.3 on 2022-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_individu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='birth_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individu',
            name='generation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
