# Generated by Django 4.1.3 on 2022-12-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_individu_spouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='isIncomingSpouse',
            field=models.BooleanField(default=False),
        ),
    ]
