# Generated by Django 4.1.3 on 2023-01-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='sFather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individu',
            name='sMother',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
